### ISSUE TITLE
[Suggestion] Desktop app will be helpful  more

### ISSUE THREAD

**Issue by santoshgistto** [mllrr96/Medusa-Admin-Flutter#26]
Desktop app will be helpful  more

Thanks for this

**Comment by mllrr96** [comment]
It should not be very difficult to make this into a desktop app, of course ui refactor and improvement to fit desktop size is needed. As of now this is not a proirity

**Comment by SalahAdDin** [comment]
> Desktop app will be helpful more
> 
> Thanks for this

In this case you can make Medusa a PWA...
